pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
  environment {     
    DOCKERHUB_CREDENTIALS= credentials('dockern')     
  } 
  stages {
    stage('Clone') {
      steps {
        container('maven') {
          git branch: 'master', changelog: false, poll: false, url: 'https://github.com/varma-nareshn/cicd-app1.git' , credentialsId: 'gitpat1'
        }
      }
    }  
    stage('Build-Jar-file') {
      steps {
        container('maven') {
          sh 'cd cicd-app1'
          sh 'mvn -f cicd-app1/pom.xml package'
        }
      }
    }
  
    stage('Build-Docker-Image') {
      steps {
        container('docker') {
          sh 'ls -ltr cicd-app1'
          sh 'docker build  -f cicd-app1/Dockerfile -t testimage .'
          sh 'docker tag testimage var0761/testimage:v1'
        }
      }
    }
    stage('Login-Into-Docker') {
      steps {
        container('docker') {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'                 
	echo 'Login Completed'
      }
    }
    }
     stage('Push-Images-Docker-to-DockerHub') {
      steps {
        container('docker') {
          sh 'docker push var0761/testimage:v1'
      }
    }
     }
  }
    post {
      always {
        container('docker') {
          sh 'docker logout'
      }
      }
    }
}
